"""Add deleted column to Post model

Revision ID: 87a4ce2be2f0
Revises: d26c5b09b9bd
Create Date: 2025-05-28 18:56:38.051950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a4ce2be2f0'
down_revision = 'd26c5b09b9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
