"""Add privacy_level to Profile

Revision ID: e8de2f1811db
Revises: 87a4ce2be2f0
Create Date: 2025-05-31 09:59:44.716854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8de2f1811db'
down_revision = '87a4ce2be2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('privacy_level')

    # ### end Alembic commands ###
